/*
 * Copyright (C) 2025 SamuelParanhos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.gui;

import io.github.guisso.javasepersistencewithhibernateorm.beta.equipe.Equipe;
import io.github.guisso.javasepersistencewithhibernateorm.beta.equipe.EquipeRepository;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author SamuelParanhos
 */
public class CadastroEquipe extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroEquipe.class.getName());
    private final EquipeRepository equipeRepository;
    private final DefaultListModel<Equipe> modelEquipe;

    /**
     * Creates new form CadastroEquipe
     */
    public CadastroEquipe() {
        equipeRepository = new EquipeRepository();
        modelEquipe = new DefaultListModel<>();
        modelEquipe.addAll(equipeRepository.findAll());
        

        initComponents();
        lblAlerta.setVisible(false);
        javax.swing.ButtonGroup radioGroup = new javax.swing.ButtonGroup();
        radioGroup.add(radNaoExcluidos);
        radioGroup.add(radExcluidos);
        radNaoExcluidos.setSelected(true);

    }

    public void clear() {
        txtNome.setText("");
        txtTecnico.setText("");
    }

    public void enableTrash(boolean status) {
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnEsvaziar.setEnabled(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTecnico = new javax.swing.JTextField();
        lblTecncio = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        lstEquipe = new javax.swing.JScrollPane();
        lstEquipes = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTecnicoActionPerformed(evt);
            }
        });

        lblTecncio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTecncio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTecncio.setText("Tecnico:");

        btnCadastrar.setText("Salvar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(77, 77, 77))
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTecncio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTecncio)
                    .addComponent(txtTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCadastrar)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastro", pnlCadastro);

        lstEquipes.setModel(modelEquipe);
        lstEquipe.setViewportView(lstEquipes);

        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setText("Lixeira:");

        lblAlerta.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lblAlerta.setText("Alerta");

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlerta)
                    .addComponent(lstEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(radNaoExcluidos)
                    .addComponent(radExcluidos)
                    .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEsvaziar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(lblLixeira)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstEquipe)
                .addContainerGap())
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(radNaoExcluidos)
                .addGap(18, 18, 18)
                .addComponent(radExcluidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(lblLixeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRestaurar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirLixeira)
                .addGap(18, 18, 18)
                .addComponent(btnEsvaziar)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo.setText("Equipe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String nome = txtNome.getText();
        String tecnico = txtTecnico.getText();

        JOptionPane.showMessageDialog(this, "Equipe: " + nome + " Registrada!");

        Equipe e1 = new Equipe();

        e1.setNome(nome);
        e1.setTecnico(tecnico);

        equipeRepository.saveOrUpdate(e1);

        clear();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTecnicoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (lstEquipes.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um atleta");
            return;
        }

        if (lstEquipes.getSelectedIndices().length == 1) {
            Equipe selected = lstEquipes.getSelectedValue();

            equipeRepository.moveToTrash(selected);
            modelEquipe.removeElement(selected);
        } else {

            List<Equipe> selection = lstEquipes.getSelectedValuesList();

            equipeRepository.moveToTrash(selection);
            for (Equipe aux : selection) {
                modelEquipe.removeElement(aux);
            }
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed

        if (lstEquipes.getSelectedIndices().length == 0) {
            return;
        }

        if (lstEquipes.getSelectedIndices().length == 1) {

            Equipe selected = lstEquipes.getSelectedValue();

            equipeRepository.restoreFromTrash(selected);

            modelEquipe.removeElement(selected);

        } else {
            List<Equipe> selection = lstEquipes.getSelectedValuesList();

            equipeRepository.restoreFromTrash(selection);

            for (Equipe aux : selection) {
                modelEquipe.removeElement(aux);
            }
        }

        JOptionPane.showMessageDialog(this, "Equipe(s) restaurada(s) com sucesso!");

    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            enableTrash(false);
        } else {
        }

        modelEquipe.clear();
        modelEquipe.addAll(equipeRepository.loadFromDataBase());


    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            enableTrash(true);
        }

        modelEquipe.clear();
        modelEquipe.addAll(equipeRepository.loadFromTrash());
    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
        if (lstEquipes.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um atleta");
            return;
        }
        if (lstEquipes.getSelectedIndices().length == 1) {
            Equipe selected = lstEquipes.getSelectedValue();

            equipeRepository.delete(selected);
            modelEquipe.removeElement(selected);
        } else {

            List<Equipe> selection = lstEquipes.getSelectedValuesList();

            for (Equipe aux : selection) {
                equipeRepository.delete(aux);
                modelEquipe.removeElement(aux);
            }
        }

    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed

        List<Equipe> selection = equipeRepository.loadFromTrash();

        if (selection == null || selection.isEmpty()) {
            return;
        }
        try {
            for (Equipe aux : selection) {
                equipeRepository.delete(aux);
            }
            modelEquipe.clear();

        } catch (Exception e) {
            System.err.println("Erro ao deletar Equipes. A operação foi revertida. Detalhes: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showWarning(String warning){
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        
        timer.setRepeats(false);
        timer.start();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroEquipe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTecncio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane lstEquipe;
    private javax.swing.JList<Equipe> lstEquipes;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTecnico;
    // End of variables declaration//GEN-END:variables

}
