/*
 * Copyright (C) 2025 robert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.gui;
import io.github.guisso.javasepersistencewithhibernateorm.beta.setvolei.SetVoleiRepository;
import io.github.guisso.javasepersistencewithhibernateorm.beta.setvolei.SetVolei;
import javax.swing.DefaultListModel;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author robert
 */
public class CadastroSetVolei extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroSetVolei.class.getName());
    private final SetVoleiRepository setVoleiRepository;
    private DefaultListModel<SetVolei> modelSetVolei;
    /**
     * Creates new form CadastroSetVolei
     */
    public CadastroSetVolei() {
        
        setVoleiRepository = new SetVoleiRepository();
        modelSetVolei = new DefaultListModel<>();
        modelSetVolei.addAll(setVoleiRepository.findAll());
        
        initComponents();
        
        lblAlerta.setVisible(false);
        
        javax.swing.ButtonGroup radioGroup = new javax.swing.ButtonGroup();
        radioGroup.add(radNaoExcluidos);
        radioGroup.add(radExcluidos);
        radNaoExcluidos.setSelected(true);
    }
    public void cadastrarSetVolei()
    {
        SetVolei setVolei = new SetVolei();
        
        String pontuacao1Aux = txtPontuacao1.getText();
        String pontuacao2Aux = txtPontuacao2.getText();
        String numeroSetAux = txtNumeroSet.getText();
        String equipe1 = txtEquipe1.getText();
        String equipe2 = txtEquipe2.getText();
        String timeVencedor = txtTimeVencedor.getText(); 
        
        if(pontuacao1Aux.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "O campo 'Pontuação 1' é obrigatório.\n");
            return;
        }
        if(pontuacao2Aux.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "O campo 'Pontuação 2' é obrigatório.\n");
            return;
        }
        if(numeroSetAux.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "O campo 'Numero do Set'é obrigatório.\n");
            return;
        }    
        
        if (equipe1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Equipe 1' é obrigatório.\n");
            return;
        }
        if (equipe2 == null) {
             JOptionPane.showMessageDialog(this, "O campo 'Equipe 2' é obrigatório.\n");
             return;
        }
        if (timeVencedor == null) {
             JOptionPane.showMessageDialog(this, "O campo 'Vencedor' é obrigatório.\n");
             return;             
        }
        
        Integer pontuacao1 = Integer.parseInt(txtPontuacao1.getText());
        Integer pontuacao2 = Integer.parseInt(txtPontuacao1.getText());
        Integer numeroSet = Integer.parseInt(txtNumeroSet.getText());
         
        setVolei.setPontuacao1(pontuacao1);
        setVolei.setPontuacao2(pontuacao2);
        setVolei.setNumeroSet(numeroSet);
        setVolei.setEquipe1(equipe1);
        setVolei.setEquipe2(equipe2);
        setVolei.setVencedor(timeVencedor);
        
        setVoleiRepository.saveOrUpdate(setVolei);
    }
    
    public void showWarning(String warning){
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        
        timer.setRepeats(false);
        timer.start();
    }
    
    public void clear()
    {
        txtPontuacao1.setText("");
        txtPontuacao2.setText("");
        txtNumeroSet.setText("");
        txtEquipe1.setText("");
        txtEquipe2.setText("");
        txtTimeVencedor.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tabListagemSets = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblPontuacaoTime1 = new javax.swing.JLabel();
        lblEquipe1 = new javax.swing.JLabel();
        lblEquipe2 = new javax.swing.JLabel();
        txtEquipe1 = new javax.swing.JTextField();
        lblPontuacao2 = new javax.swing.JLabel();
        txtEquipe2 = new javax.swing.JTextField();
        lblNumeroSet = new javax.swing.JLabel();
        lblTimeVencedor = new javax.swing.JLabel();
        txtPontuacao1 = new javax.swing.JTextField();
        txtTimeVencedor = new javax.swing.JTextField();
        txtPontuacao2 = new javax.swing.JTextField();
        txtNumeroSet = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSetVolei = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        lblLixeira = new javax.swing.JLabel();
        lblAlerta = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPontuacaoTime1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPontuacaoTime1.setText("Pontos do Time 1:");

        lblEquipe1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEquipe1.setText("Equipe 1:");

        lblEquipe2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEquipe2.setText("Equipe 2:");

        lblPontuacao2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPontuacao2.setText("Pontos do Time 2:");

        lblNumeroSet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumeroSet.setText("Nº do set:");

        lblTimeVencedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTimeVencedor.setText("Vencedor:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPontuacaoTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPontuacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPontuacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPontuacao2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTimeVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimeVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroSet, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeroSet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontuacaoTime1)
                    .addComponent(txtPontuacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipe1)
                    .addComponent(txtEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontuacao2)
                    .addComponent(txtPontuacao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipe2)
                    .addComponent(txtEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeVencedor)
                    .addComponent(txtTimeVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroSet)
                    .addComponent(txtNumeroSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnCadastrar)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tabListagemSets.addTab("Cadastro de Set", jPanel2);

        lstSetVolei.setModel(modelSetVolei);
        jScrollPane1.setViewportView(lstSetVolei);

        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setText("Lixeira:");

        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lblAlerta.setText("Alerta");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radNaoExcluidos)
                    .addComponent(radExcluidos)
                    .addComponent(lblLixeira)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestaurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlerta)
                .addGap(200, 200, 200))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblAlerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radExcluidos)
                        .addGap(12, 12, 12)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(lblLixeira)
                        .addGap(12, 12, 12)
                        .addComponent(btnExcluirLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEsvaziar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestaurar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabListagemSets.addTab("Listagem de Set", jPanel3);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo.setText("Set's Volei");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabListagemSets)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(tabListagemSets, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        JOptionPane.showMessageDialog(this, "Set cadastrado com sucesso!");
        cadastrarSetVolei();
        clear();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
        enableTrash(false);

        modelSetVolei.clear();
        modelSetVolei.addAll(setVoleiRepository.loadFromDataBase());
    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
         if(evt.getStateChange() == ItemEvent.SELECTED)
            enableTrash(true);
        
        modelSetVolei.clear();
        modelSetVolei.addAll(setVoleiRepository.loadFromTrash());
    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(lstSetVolei.getSelectedIndices().length == 0){
            //showWarning("Selecione ao menos um atleta");
            return;
        }
        if(lstSetVolei.getSelectedIndices().length == 1){
            SetVolei selected = lstSetVolei.getSelectedValue();
            
        setVoleiRepository.moveToTrash(selected);
        modelSetVolei.removeElement(selected);
        }else{
        
            List<SetVolei> selection = lstSetVolei.getSelectedValuesList();
                
            setVoleiRepository.moveToTrash(selection);
            for(SetVolei aux : selection)
            {
                modelSetVolei.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
         if(lstSetVolei.getSelectedIndices().length == 0){
            //showWarning("Selecione ao menos um atleta");
            return;
        }
         if(lstSetVolei.getSelectedIndices().length == 1){
            SetVolei selected = lstSetVolei.getSelectedValue();
            
        setVoleiRepository.delete(selected);
        modelSetVolei.removeElement(selected);
        }else{
        
            List<SetVolei> selection = lstSetVolei.getSelectedValuesList();         
            
            for(SetVolei aux : selection)
            {
                setVoleiRepository.delete(aux);
                modelSetVolei.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        List<SetVolei> selection = setVoleiRepository.loadFromTrash();

    if (selection == null || selection.isEmpty()) {
        return;
    }
    try {
        for (SetVolei aux : selection) {
            setVoleiRepository.delete(aux);
        }  
        modelSetVolei.clear();

    } catch (Exception e) {
        System.err.println("Erro ao deletar atletas. A operação foi revertida. Detalhes: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (lstSetVolei.getSelectedIndices().length == 0) {
            return;
        }

        if (lstSetVolei.getSelectedIndices().length == 1) {

            SetVolei selected = lstSetVolei.getSelectedValue();

            setVoleiRepository.restoreFromTrash(selected);

            modelSetVolei.removeElement(selected);

        } else {
            List<SetVolei> selection = lstSetVolei.getSelectedValuesList();

            setVoleiRepository.restoreFromTrash(selection);

            for (SetVolei aux : selection) {
                modelSetVolei.removeElement(aux);
            }
        }

        JOptionPane.showMessageDialog(this, "Atleta(s) restaurado(s) com sucesso!");
    }//GEN-LAST:event_btnRestaurarActionPerformed
    
    public void enableTrash(boolean status)
    {
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnEsvaziar.setEnabled(status);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroSetVolei().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblEquipe1;
    private javax.swing.JLabel lblEquipe2;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblNumeroSet;
    private javax.swing.JLabel lblPontuacao2;
    private javax.swing.JLabel lblPontuacaoTime1;
    private javax.swing.JLabel lblTimeVencedor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<SetVolei> lstSetVolei;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JTabbedPane tabListagemSets;
    private javax.swing.JTextField txtEquipe1;
    private javax.swing.JTextField txtEquipe2;
    private javax.swing.JTextField txtNumeroSet;
    private javax.swing.JTextField txtPontuacao1;
    private javax.swing.JTextField txtPontuacao2;
    private javax.swing.JTextField txtTimeVencedor;
    // End of variables declaration//GEN-END:variables
}
