/*
 * Copyright (C) 2025 rdpp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.gui;

import io.github.guisso.javasepersistencewithhibernateorm.beta.partida.Partida;
import io.github.guisso.javasepersistencewithhibernateorm.beta.partida.PartidaRepository;
import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Samuel Paranhos
 */
public class CadastroPartida extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroPartida.class.getName());
    private final PartidaRepository partidaRepository;
    private final DefaultListModel<Partida> modelPartida;

    /* Creates new form CadastroPartida
     */
    public CadastroPartida() {
        partidaRepository = new PartidaRepository();
        modelPartida = new DefaultListModel<>();
        modelPartida.addAll(partidaRepository.findAll());
        
        initComponents();
        
        lblAlerta.setVisible(false);
        
        javax.swing.ButtonGroup radioGroup = new javax.swing.ButtonGroup();
        radioGroup.add(radNaoExcluidos);
        radioGroup.add(radExcluidos);
        radNaoExcluidos.setSelected(true);

    }

    public void clear() {
        txtNomeEquipe1.setText("");
        txtNomeEquipe2.setText("");
        txtQtdSets.setText("");
        txtVencedor.setText("");

    }

    public void enableTrash(boolean status) {
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnEsvaziar.setEnabled(status);
    }
    
    public void showWarning(String warning){
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        tabPrincipal = new javax.swing.JTabbedPane();
        pnlCadstro = new javax.swing.JPanel();
        lblEquipe1 = new javax.swing.JLabel();
        txtNomeEquipe1 = new javax.swing.JTextField();
        txtNomeEquipe2 = new javax.swing.JTextField();
        txtVencedor = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lblEquipe2 = new javax.swing.JLabel();
        lblVencedor = new javax.swing.JLabel();
        lblQtdSets = new javax.swing.JLabel();
        spnlSet = new javax.swing.JScrollPane();
        txtQtdSets = new javax.swing.JTextPane();
        pnlListagem = new javax.swing.JPanel();
        spnlLista = new javax.swing.JScrollPane();
        lstPartidas = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        lblLixeira = new javax.swing.JLabel();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrode Partidas");

        lblEquipe1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEquipe1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipe1.setText("Equipe 1:");

        txtNomeEquipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEquipe1ActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Salvar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblEquipe2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipe2.setText("Equipe 2:");

        lblVencedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVencedor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVencedor.setText("Vencedor:");

        lblQtdSets.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQtdSets.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQtdSets.setText("Quantidade de Sets:");

        spnlSet.setViewportView(txtQtdSets);

        javax.swing.GroupLayout pnlCadstroLayout = new javax.swing.GroupLayout(pnlCadstro);
        pnlCadstro.setLayout(pnlCadstroLayout);
        pnlCadstroLayout.setHorizontalGroup(
            pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadstroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQtdSets, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnlSet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadstroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        pnlCadstroLayout.setVerticalGroup(
            pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadstroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipe1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipe2)
                    .addComponent(txtNomeEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQtdSets)
                    .addComponent(spnlSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCadstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVencedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tabPrincipal.addTab("Cadastro", pnlCadstro);

        lstPartidas.setModel(modelPartida);
        spnlLista.setViewportView(lstPartidas);

        radNaoExcluidos.setText("Não Excluidos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });
        radNaoExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNaoExcluidosActionPerformed(evt);
            }
        });

        radExcluidos.setText("Excluidos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lblLixeira.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLixeira.setText("Lixeira:");

        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lblAlerta.setText("Alerta");

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radNaoExcluidos)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(spnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(radExcluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLixeira)
                            .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestaurar))
                        .addGap(17, 17, 17)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlerta)
                .addGap(187, 187, 187))
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblAlerta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spnlLista, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radNaoExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(lblLixeira)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirLixeira)
                        .addGap(12, 12, 12)
                        .addComponent(btnEsvaziar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRestaurar)))
                .addContainerGap())
        );

        tabPrincipal.addTab("Listagem", pnlListagem);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPrincipal)
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo.setText("Partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeEquipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEquipe1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEquipe1ActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String equipe1 = txtNomeEquipe1.getText();
        String equipe2 = txtNomeEquipe2.getText();
        String aux = txtQtdSets.getText();
        String vencedor = txtVencedor.getText();
        
        if(aux == null)
        {
            JOptionPane.showMessageDialog(this, "O campo 'Quantidade de Sets' é obrigatório.\n");
            return;
        }
        
        Integer qtdSets = Integer.parseInt(txtQtdSets.getText());
        
        if (equipe1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Equipe 1' é obrigatório.\n");
            return;
        }
        if (equipe2.isEmpty()) {
             JOptionPane.showMessageDialog(this, "O campo 'Equipe 2' é obrigatório.\n");
             return;
        }
        
        if (vencedor.isEmpty()) {
             JOptionPane.showMessageDialog(this, "O campo 'Vencedor' é obrigatório.\n");
             return;             
        }


        JOptionPane.showMessageDialog(this, "Partida Registrada!");

        Partida p1 = new Partida();
        p1.setEquipe1(equipe1);
        p1.setEquipe2(equipe2);
        p1.setQuantidadeSets(qtdSets);
        p1.setVencedor(vencedor);

        partidaRepository.saveOrUpdate(p1);

        clear();

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            enableTrash(false);
        } else {
        }

        modelPartida.clear();
        modelPartida.addAll(partidaRepository.loadFromDataBase());

    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            enableTrash(true);
        }

        modelPartida.clear();
        modelPartida.addAll(partidaRepository.loadFromTrash());

    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       if (lstPartidas.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um atleta");
            return;
        }

        if (lstPartidas.getSelectedIndices().length == 1) {
            Partida selected = lstPartidas.getSelectedValue();

            partidaRepository.moveToTrash(selected);
            modelPartida.removeElement(selected);
        } else {

            List<Partida> selection = lstPartidas.getSelectedValuesList();

            partidaRepository.moveToTrash(selection);
            for (Partida aux : selection) {
                modelPartida.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
         if (lstPartidas.getSelectedIndices().length == 0) {
            showWarning("Selecione ao menos um atleta");
            return;
        }
        if (lstPartidas.getSelectedIndices().length == 1) {
            Partida selected = lstPartidas.getSelectedValue();

            partidaRepository.delete(selected);
            modelPartida.removeElement(selected);
        } else {

            List<Partida> selection = lstPartidas.getSelectedValuesList();

            for (Partida aux : selection) {
                partidaRepository.delete(aux);
                modelPartida.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        List<Partida> selection = partidaRepository.loadFromTrash();

        if (selection == null || selection.isEmpty()) {
            return;
        }
        try {
            for (Partida aux : selection) {
                partidaRepository.delete(aux);
            }
            modelPartida.clear();

        } catch (Exception e) {
            System.err.println("Erro ao deletar Equipes. A operação foi revertida. Detalhes: " + e.getMessage());
        }


    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (lstPartidas.getSelectedIndices().length == 0) {
            return;
        }

        if (lstPartidas.getSelectedIndices().length == 1) {

            Partida selected = lstPartidas.getSelectedValue();

            partidaRepository.restoreFromTrash(selected);

            modelPartida.removeElement(selected);

        } else {
            List<Partida> selection = lstPartidas.getSelectedValuesList();

            partidaRepository.restoreFromTrash(selection);

            for (Partida aux : selection) {
                modelPartida.removeElement(aux);
            }
        }

        JOptionPane.showMessageDialog(this, "Equipe(s) restaurada(s) com sucesso!");
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void radNaoExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNaoExcluidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNaoExcluidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroPartida().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblEquipe1;
    private javax.swing.JLabel lblEquipe2;
    private javax.swing.JLabel lblLixeira;
    private javax.swing.JLabel lblQtdSets;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVencedor;
    private javax.swing.JList<Partida> lstPartidas;
    private javax.swing.JPanel pnlCadstro;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane spnlLista;
    private javax.swing.JScrollPane spnlSet;
    private javax.swing.JTabbedPane tabPrincipal;
    private javax.swing.JTextField txtNomeEquipe1;
    private javax.swing.JTextField txtNomeEquipe2;
    private javax.swing.JTextPane txtQtdSets;
    private javax.swing.JTextField txtVencedor;
    // End of variables declaration//GEN-END:variables

}
