/*
 * Copyright (C) 2025 Filipe
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.gui;

import com.github.lgooddatepicker.components.DatePickerSettings;
import io.github.guisso.javasepersistencewithhibernateorm.beta.eventoesportivo.EventoEsportivo;
import io.github.guisso.javasepersistencewithhibernateorm.beta.eventoesportivo.EventoEsportivoRepository;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.awt.event.ItemEvent;

/**
 *
 * @author Filipe
 */
public class CadastroEvento extends javax.swing.JFrame {

    private final DefaultListModel<EventoEsportivo> modelEvento;
    private final EventoEsportivoRepository repository;

    /**
     * Creates new form CadastroEvento
     */
    public CadastroEvento() {
        
        // Repository for CRUD operations
        repository = new EventoEsportivoRepository();
        
        //Default Evento list model
        modelEvento = new DefaultListModel<>();
        modelEvento.addAll(repository.findAll());
        
        initComponents();
        
        javax.swing.ButtonGroup radioGroup = new javax.swing.ButtonGroup();
        radioGroup.add(radNaoExcluidos);
        radioGroup.add(radExcluidos);
        radNaoExcluidos.setSelected(true);
        
        lblAlerta.setVisible(false);
        
        //DatePicker settings
         DatePickerSettings settings
                = new DatePickerSettings(Locale.of("pt", "BR"));
        
        // Date format
        settings.setFormatForDatesCommonEra(
                DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        settings.setFormatForDatesBeforeCommonEra(
                DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        // Translations
        settings.setTranslationToday("Hoje");
        settings.setTranslationClear("Limpar");

        // Same font as text fields
        Font defaultFont = txtNome.getFont();

        settings.setFontValidDate(defaultFont);
        settings.setFontInvalidDate(defaultFont);
        settings.setFontVetoedDate(defaultFont);
        
        // Applying settings
        dtpData.setSettings(settings);
        
        // Date range limits
        settings.setDateRangeLimits(LocalDate.now(), LocalDate.MAX);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabEventoEsportivo = new javax.swing.JTabbedPane();
        pnlCadastro = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblLocal = new javax.swing.JLabel();
        lblIngresso = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtLocal = new javax.swing.JTextField();
        txtIngresso = new javax.swing.JTextField();
        dtpData = new com.github.lgooddatepicker.components.DatePicker();
        btnSalvar = new javax.swing.JButton();
        pnlListagem = new javax.swing.JPanel();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLRestaurar = new javax.swing.JButton();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        scrEvento = new javax.swing.JScrollPane();
        lstEvento = new javax.swing.JList<>();
        lblAlerta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Evento Esportivo");

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");
        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblData.setText("Data:");
        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblLocal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLocal.setText("Local:");
        lblLocal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblIngresso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIngresso.setText("Ingresso:");
        lblIngresso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCadastroLayout = new javax.swing.GroupLayout(pnlCadastro);
        pnlCadastro.setLayout(pnlCadastroLayout);
        pnlCadastroLayout.setHorizontalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(pnlCadastroLayout.createSequentialGroup()
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                            .addComponent(lblIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome)
                            .addComponent(dtpData, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtLocal))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlCadastroLayout.setVerticalGroup(
            pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(dtpData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocal)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngresso)
                    .addComponent(txtIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        tabEventoEsportivo.addTab("Cadastro", pnlCadastro);

        radNaoExcluidos.setSelected(true);
        radNaoExcluidos.setText("Não excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });
        radExcluidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radExcluidosActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Lixeira:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLRestaurar.setText("Restaurar");
        btnLRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLRestaurarActionPerformed(evt);
            }
        });

        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        lstEvento.setModel(modelEvento);
        lstEvento.setToolTipText("");
        scrEvento.setViewportView(lstEvento);

        lblAlerta.setText("Alerta");
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlerta.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setText("Eventos:");

        javax.swing.GroupLayout pnlListagemLayout = new javax.swing.GroupLayout(pnlListagem);
        pnlListagem.setLayout(pnlListagemLayout);
        pnlListagemLayout.setHorizontalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(scrEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListagemLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAlerta)
                        .addGap(56, 56, 56)))
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radExcluidos)
                    .addComponent(radNaoExcluidos)
                    .addComponent(jLabel1)
                    .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLRestaurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEsvaziar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlListagemLayout.setVerticalGroup(
            pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNaoExcluidos)
                    .addComponent(lblAlerta)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListagemLayout.createSequentialGroup()
                        .addComponent(radExcluidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLRestaurar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirLixeira)
                        .addGap(18, 18, 18)
                        .addComponent(btnEsvaziar)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addComponent(scrEvento)))
        );

        tabEventoEsportivo.addTab("Listagem", pnlListagem);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Evento Esportivo");
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabEventoEsportivo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabEventoEsportivo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void clear()
    {
        txtNome.setText("");
        dtpData.setText("");
        txtLocal.setText("");
        txtIngresso.setText("");
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        EventoEsportivo ee = new EventoEsportivo();
        
        String nome = txtNome.getText();
        String local = txtLocal.getText();
        String aux = txtIngresso.getText();
        LocalDate data = dtpData.getDate();
        
        if(aux == null)
        {
            JOptionPane.showMessageDialog(this, "O campo 'Ingresso' é obrigatório.\n");
            return;
        }
        
        Double ingresso = Double.parseDouble(txtIngresso.getName());
                
        ee.setNome(nome);
        ee.setData(data);
        ee.setLocal(local);
        ee.setIngressoTime(ingresso);
       
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Nome' é obrigatório.\n");
            return;
        }
        if (data == null) {
             JOptionPane.showMessageDialog(this, "O campo 'Data' é obrigatório.\n");
             return;
        }
        if (data == null) {
             JOptionPane.showMessageDialog(this, "O campo 'Data de nascimento' é obrigatório.\n");
             return;             
        }

       
        
        try {
            repository.saveOrUpdate(ee);
            JOptionPane.showMessageDialog(this, "Evento: " + 
                    ee.getNome() + ", salvo com sucesso !");
            clear();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Falha ao gravar o aluno no banco de dados",
                    "Erro: ",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void radExcluidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radExcluidosActionPerformed

    }//GEN-LAST:event_radExcluidosActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            enableTrash(false);
            
            modelEvento.clear();
            modelEvento.addAll(repository.findAll());
            
        }
    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            enableTrash(true);
            
            modelEvento.clear();
            modelEvento.addAll(repository.loadFromTrash());
        }
    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(lstEvento.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um Evento");
            return;
        }
        
        if(lstEvento.getSelectedIndices().length == 1){
            
            EventoEsportivo selected = lstEvento.getSelectedValue();
            repository.moveToTrash(selected);
            modelEvento.removeElement(selected);
        
        }else{
            List<EventoEsportivo> selection = lstEvento.getSelectedValuesList();
            
            repository.moveToTrash(selection);
            
            for(EventoEsportivo aux : selection){
                modelEvento.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLRestaurarActionPerformed
        if (lstEvento.getSelectedIndices().length == 0) {
            return;
        }

        if (lstEvento.getSelectedIndices().length == 1) {

            EventoEsportivo selected = lstEvento.getSelectedValue();

            repository.restoreFromTrash(selected);

            modelEvento.removeElement(selected);

        } else {
            List<EventoEsportivo> selection = lstEvento.getSelectedValuesList();

            repository.restoreFromTrash(selection);

            for (EventoEsportivo aux : selection) {
                modelEvento.removeElement(aux);
            }
        }

        JOptionPane.showMessageDialog(this, "Evento(s) restaurado(s) com sucesso!");
    }//GEN-LAST:event_btnLRestaurarActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
        if(lstEvento.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um atleta");
            return;
        }
         if(lstEvento.getSelectedIndices().length == 1){
            EventoEsportivo selected = lstEvento.getSelectedValue();
            
        repository.delete(selected);
        modelEvento.removeElement(selected);
        }else{
        
            List<EventoEsportivo> selection = lstEvento.getSelectedValuesList();         
            
            for(EventoEsportivo aux : selection)
            {
                repository.delete(aux);
                modelEvento.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
        List<EventoEsportivo> selection = repository.loadFromTrash();

    if (selection == null || selection.isEmpty()) {
        return;
    }
    try {
        for (EventoEsportivo aux : selection) {
                repository.delete(aux);
        }  
        modelEvento.clear();

    } catch (Exception e) {
        System.err.println("Erro ao deletar atletas. A operação foi revertida. Detalhes: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEvento().setVisible(true);
            }
        });
    }
    
    public void enableTrash(boolean status){
        btnExcluir.setEnabled(!status);
        btnLRestaurar.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnEsvaziar.setEnabled(status);  
    }
    
    public void showWarning(String warning){
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        
        timer.setRepeats(false);
        timer.start();
    }
    
    public void clearFields(){
        txtNome.setText(null);
        txtNome.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnLRestaurar;
    private javax.swing.JButton btnSalvar;
    private com.github.lgooddatepicker.components.DatePicker dtpData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblIngresso;
    private javax.swing.JLabel lblLocal;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<EventoEsportivo> lstEvento;
    private javax.swing.JPanel pnlCadastro;
    private javax.swing.JPanel pnlListagem;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JScrollPane scrEvento;
    private javax.swing.JTabbedPane tabEventoEsportivo;
    private javax.swing.JTextField txtIngresso;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
