/*
 * Copyright (C) 2025 robert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package io.github.guisso.javasepersistencewithhibernateorm.beta.gui;

import com.github.lgooddatepicker.components.DatePickerSettings;
import io.github.guisso.javasepersistencewithhibernateorm.beta.tecnico.TecnicoRepository;
import io.github.guisso.javasepersistencewithhibernateorm.beta.tecnico.Tecnico;
import java.awt.Font;
import java.awt.event.ItemEvent;
import javax.swing.DefaultListModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author robert
 */
public class CadastroTecnico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroTecnico.class.getName());
    private final TecnicoRepository tecnicoRepository;
    private final DefaultListModel<Tecnico> modelTecnico;
    /**
     * Creates new form CadastroTecnico
     */
    public CadastroTecnico() {
        tecnicoRepository = new TecnicoRepository();
        modelTecnico = new DefaultListModel<>();
        modelTecnico.addAll(tecnicoRepository.findAll());
        
        initComponents();
        
        lblAlerta.setVisible(false);
        
        //DatePicker settings
         DatePickerSettings settings
                = new DatePickerSettings(Locale.of("pt", "BR"));
        
        // Date format
        settings.setFormatForDatesCommonEra(
                DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        settings.setFormatForDatesBeforeCommonEra(
                DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        // Translations
        settings.setTranslationToday("Hoje");
        settings.setTranslationClear("Limpar");

        // Same font as text fields
        Font defaultFont = txtNome.getFont();

        settings.setFontValidDate(defaultFont);
        settings.setFontInvalidDate(defaultFont);
        settings.setFontVetoedDate(defaultFont);
        
        // Applying settings
        dtpDataNascimento.setSettings(settings);
        
        // Date range limits
        settings.setDateRangeLimits(LocalDate.MIN, LocalDate.now());
        
        javax.swing.ButtonGroup radioGroup = new javax.swing.ButtonGroup();
        radioGroup.add(radNaoExcluidos);
        radioGroup.add(radExcluidos);
        radNaoExcluidos.setSelected(true);
        
    }
    
    public void cadastrarTecnico()
    {
        String nome = txtNome.getText();
        Long CPF = Long.parseLong(txtCPF.getText());
        String equipe = txtEquipe.getText();
        LocalDate data = dtpDataNascimento.getDate();
        
        Tecnico tecnico = new Tecnico();
        
        tecnico.setNome(nome);
        tecnico.setCpf(CPF);
        tecnico.setEquipe(equipe);
        tecnico.setDate(data);
        
        tecnicoRepository.saveOrUpdate(tecnico);   
    }
    
    public void clear()
    {
      txtNome.setText("");
      txtCPF.setText("");
      txtEquipe.setText("");
      dtpDataNascimento.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        tabListagemTecnico = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblEquipe = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtEquipe = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        dtpDataNascimento = new com.github.lgooddatepicker.components.DatePicker();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTecnicos = new javax.swing.JList<>();
        radNaoExcluidos = new javax.swing.JRadioButton();
        radExcluidos = new javax.swing.JRadioButton();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExcluirLixeira = new javax.swing.JButton();
        btnEsvaziar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        lblAlerta = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("Nome:");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCPF.setText("CPF:");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblData.setText("Data de Nascimento:");

        lblEquipe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEquipe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipe.setText("Equipe:");

        btnCadastrar.setText("Salvar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblData)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(dtpDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(dtpDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEquipe)
                    .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        tabListagemTecnico.addTab("Cadastro", jPanel1);

        lstTecnicos.setModel(modelTecnico);
        jScrollPane1.setViewportView(lstTecnicos);

        radNaoExcluidos.setText("Não Excluídos");
        radNaoExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radNaoExcluidosItemStateChanged(evt);
            }
        });

        radExcluidos.setText("Excluídos");
        radExcluidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radExcluidosItemStateChanged(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Lixeira:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnExcluirLixeira.setText("Excluir");
        btnExcluirLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLixeiraActionPerformed(evt);
            }
        });

        btnEsvaziar.setText("Esvaziar");
        btnEsvaziar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsvaziarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        lblAlerta.setText("Alerta");
        lblAlerta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radExcluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radNaoExcluidos)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEsvaziar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlerta)
                .addGap(165, 165, 165))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAlerta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(radNaoExcluidos)
                        .addGap(18, 18, 18)
                        .addComponent(radExcluidos)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirLixeira)
                        .addGap(18, 18, 18)
                        .addComponent(btnEsvaziar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestaurar)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabListagemTecnico.addTab("Listagem", jPanel2);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTitulo.setText("Tecnico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabListagemTecnico)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabListagemTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        JOptionPane.showMessageDialog(this, "Tecnico cadastrado com sucesso!");
        cadastrarTecnico();
        clear();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void radNaoExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radNaoExcluidosItemStateChanged
     if(evt.getStateChange() == ItemEvent.SELECTED)
        enableTrash(false);

        modelTecnico.clear();
        modelTecnico.addAll(tecnicoRepository.loadFromDataBase());
    }//GEN-LAST:event_radNaoExcluidosItemStateChanged

    private void radExcluidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radExcluidosItemStateChanged
           if(evt.getStateChange() == ItemEvent.SELECTED)
            enableTrash(true);
        
        modelTecnico.clear();
        modelTecnico.addAll(tecnicoRepository.loadFromTrash());
    }//GEN-LAST:event_radExcluidosItemStateChanged

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(lstTecnicos.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um atleta");
            return;
        }
        if(lstTecnicos.getSelectedIndices().length == 1){
            Tecnico selected = lstTecnicos.getSelectedValue();
            
        tecnicoRepository.moveToTrash(selected);
        modelTecnico.removeElement(selected);
        }else{
        
            List<Tecnico> selection = lstTecnicos.getSelectedValuesList();
                
            tecnicoRepository.moveToTrash(selection);
            for(Tecnico aux : selection)
            {
                modelTecnico.removeElement(aux);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnExcluirLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLixeiraActionPerformed
        if(lstTecnicos.getSelectedIndices().length == 0){
            showWarning("Selecione ao menos um atleta");
            return;
        }
         if(lstTecnicos.getSelectedIndices().length == 1){
            Tecnico selected = lstTecnicos.getSelectedValue();
            
        tecnicoRepository.delete(selected);
        modelTecnico.removeElement(selected);
        }else{
        
            List<Tecnico> selection = lstTecnicos.getSelectedValuesList();         
            
            for(Tecnico aux : selection)
            {
                tecnicoRepository.delete(aux);
                modelTecnico.removeElement(aux);
            }
        }
       
    }//GEN-LAST:event_btnExcluirLixeiraActionPerformed

    private void btnEsvaziarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsvaziarActionPerformed
       
    List<Tecnico> selection = tecnicoRepository.loadFromTrash();

    if (selection == null || selection.isEmpty()) {
        return;
    }
    try {
        for (Tecnico aux : selection) {
            tecnicoRepository.delete(aux);
        }  
        modelTecnico.clear();

    } catch (Exception e) {
        System.err.println("Erro ao deletar atletas. A operação foi revertida. Detalhes: " + e.getMessage());
    }
    }//GEN-LAST:event_btnEsvaziarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        if (lstTecnicos.getSelectedIndices().length == 0) {
            return;
        }

        if (lstTecnicos.getSelectedIndices().length == 1) {

            Tecnico selected = lstTecnicos.getSelectedValue();

            tecnicoRepository.restoreFromTrash(selected);

            modelTecnico.removeElement(selected);

        } else {
            List<Tecnico> selection = lstTecnicos.getSelectedValuesList();

            tecnicoRepository.restoreFromTrash(selection);

            for (Tecnico aux : selection) {
                modelTecnico.removeElement(aux);
            }
        }

        JOptionPane.showMessageDialog(this, "Tecnico(s) restaurada(s) com sucesso!");
    }//GEN-LAST:event_btnRestaurarActionPerformed
     public void enableTrash(boolean status)
    {
        btnExcluir.setEnabled(!status);
        btnRestaurar.setEnabled(status);
        btnExcluirLixeira.setEnabled(status);
        btnEsvaziar.setEnabled(status);
    }
     
     public void showWarning(String warning){
        lblAlerta.setText(warning);
        lblAlerta.setVisible(true);
        
        Timer timer = new Timer(4000, (e) -> {
            lblAlerta.setVisible(false);
            ((Timer) e.getSource()).stop();
        });
        
        timer.setRepeats(false);
        timer.start();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroTecnico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsvaziar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirLixeira;
    private javax.swing.JButton btnRestaurar;
    private com.github.lgooddatepicker.components.DatePicker dtpDataNascimento;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlerta;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblEquipe;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<Tecnico> lstTecnicos;
    private javax.swing.JRadioButton radExcluidos;
    private javax.swing.JRadioButton radNaoExcluidos;
    private javax.swing.JTabbedPane tabListagemTecnico;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEquipe;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
